"""update database with tables

Revision ID: 2b815a37b581
Revises:
Create Date: 2025-09-09 19:55:16.424501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b815a37b581'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    inspector = sa.inspect(op.get_bind())
    tables = inspector.get_table_names()

    # Drop children before parents
    if "feedback" in tables:
        op.drop_table("feedback")
    if "gradelog" in tables:
        op.drop_table("gradelog")
    if "submission" in tables:
        op.drop_table("submission")
    if "answer" in inspector.get_table_names():
        with op.batch_alter_table("answer") as batch_op:
            batch_op.drop_constraint("answer_question_id_fkey", type_="foreignkey")
        op.drop_table("answer")
    if "question" in inspector.get_table_names():
        op.drop_table("question")
    if "uploads" in tables:
        op.drop_table("uploads")
    if "exam" in tables:
        op.drop_table("exam")
    if "user" in tables:
        op.drop_table("user")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    question_type_enum = sa.Enum(
        'mcq', 'multi_response', 'true_false', 'short_answer', 'essay', 'code', 'numerical',
        name='question_type_enum'
    )
    user_type_enum = sa.Enum('student', 'instructor', 'admin', name='user_type_enum')
    upload_status_enum = sa.Enum('pending', 'processed', 'failed', name='upload_status')

    op.create_table(
        'program',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('name', sa.String, nullable=False, unique=True),
        sa.Column('description', sa.String),
        sa.Column('duration_years', sa.Float),
    )

    op.create_table(
        'course',
        sa.Column('id', sa.String, primary_key=True),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('program_id', sa.UUID(as_uuid=True), sa.ForeignKey('program.id')),
    )

    op.create_table(
        'semester',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('start_date', sa.TIMESTAMP, nullable=False),
        sa.Column('end_date', sa.TIMESTAMP, nullable=False),
    )

    op.create_table(
        'submission_answer',
        sa.Column('submission_id', UUID(as_uuid=True), sa.ForeignKey('submission.id')),
        sa.Column('question_id', UUID(as_uuid=True), sa.ForeignKey('question.id')),
        sa.Column('answer', Text, nullable=False),
        sa.Column('is_correct', Boolean, default=False),
        sa.PrimaryKeyConstraint('submission_id', 'question_id'),
    )

    op.create_table('answer',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('correct_option', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('answer_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('answer_pkey'))
    )
    op.create_table('gradelog',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('grader', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('graded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('submission_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], name=op.f('gradelog_submission_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gradelog_pkey'))
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('submission_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('feedback_author_id_fkey')),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], name=op.f('feedback_submission_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey'))
    )
    op.create_table(
        'exam',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('course_id', sa.String, sa.ForeignKey('course.id')),
        sa.Column('semester_id', sa.UUID(as_uuid=True), sa.ForeignKey('semester.id')),
        sa.Column('title', sa.String, nullable=False),
        sa.Column('subject', sa.String, nullable=False),
        sa.Column('duration', sa.String),
        sa.Column('pass_mark', sa.Float, server_default='40.0'),
        sa.Column('created_at', sa.TIMESTAMP, server_default=sa.func.now()),
        sa.Column('updated_at', sa.TIMESTAMP, server_default=sa.func.now()),
    )
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storage_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', upload_status_enum, autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('uploads_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('uploads_pkey'))
    )
    op.create_table(
        'exam_content',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('upload_id', sa.UUID(as_uuid=True), sa.ForeignKey('uploads.id')),
        sa.Column('text', sa.Text, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP, server_default=sa.func.now()),
    )
    op.create_table('submission',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('exam_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('submission_exam_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('submission_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('submission_pkey'))
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', user_type_enum, autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('question',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', question_type_enum, autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('exam_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('question_exam_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('question_pkey'))
    )
    # ### end Alembic commands ###