"""update models

Revision ID: 51bae42483dd
Revises: bffade732589
Create Date: 2025-11-30 10:04:47.034479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bae42483dd'
down_revision: Union[str, Sequence[str], None] = 'bffade732589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('current_question_index', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'SUBMITTED', 'EXPIRED', name='exam_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('submission', sa.Column('exam_session_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'submission', 'exam_session', ['exam_session_id'], ['id'])
    op.drop_constraint(op.f('submission_answer_question_id_fkey'), 'submission_answer', type_='foreignkey')
    op.create_foreign_key(None, 'submission_answer', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_constraint(None, 'submission_answer', type_='foreignkey')
    op.create_foreign_key(op.f('submission_answer_question_id_fkey'), 'submission_answer', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_column('submission', 'exam_session_id')
    op.drop_table('exam_session')
    # ### end Alembic commands ###
