"""add cascade delete to uploads.user_id

Revision ID: bffade732589
Revises: d1db46403e87
Create Date: 2025-11-01 10:47:01.409399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffade732589'
down_revision: Union[str, Sequence[str], None] = 'd1db46403e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uploads_user_id_fkey'), 'uploads', type_='foreignkey')
    op.create_foreign_key(None, 'uploads', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.create_foreign_key(op.f('uploads_user_id_fkey'), 'uploads', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
