"""add nullable author_id attribute to Exams

Revision ID: d07f3b5e9f7a
Revises: ca5ee058ac74
Create Date: 2025-12-11 19:27:41.832832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07f3b5e9f7a'
down_revision: Union[str, Sequence[str], None] = 'ca5ee058ac74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('author_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'exam', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_column('exam', 'author_id')
    # ### end Alembic commands ###
