"""add Curriculum, AcademicYear and ProgramLevel-Type Models

Revision ID: fa910bb7ca97
Revises: d07f3b5e9f7a
Create Date: 2025-12-17 18:56:56.098946

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa910bb7ca97'
down_revision: Union[str, Sequence[str], None] = 'd07f3b5e9f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    program_level_enum = postgresql.ENUM(
        'certificate', 'diploma', 'undergraduate', 
        'postgraduate', 'masters', 'doctorate', 
        name='program_level_enum'
    )
    program_level_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('program', sa.Column('level', program_level_enum, nullable=True))
    op.create_table('curriculum',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academic_year',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('curriculum_id', sa.UUID(), nullable=False),
    sa.Column('year_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('semester_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('semester_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('pass_mark', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'exam_session', 'exam', ['exam_id'], ['id'])
    op.add_column('program', sa.Column('code', sa.String(), nullable=False))
    op.add_column('program', sa.Column('degree_title', sa.String(), nullable=False))
    op.add_column('program', sa.Column('degree_name', sa.String(), nullable=False))
    op.add_column('program', sa.Column('department', sa.String(), nullable=False))
    op.drop_constraint(op.f('program_name_key'), 'program', type_='unique')
    op.drop_column('program', 'description')
    op.create_foreign_key(None, 'question', 'exam', ['exam_id'], ['id'])
    op.add_column('semester', sa.Column('academic_year_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'semester', 'academic_year', ['academic_year_id'], ['id'])
    op.create_foreign_key(None, 'submission', 'exam', ['exam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_constraint(None, 'semester', type_='foreignkey')
    op.drop_column('semester', 'academic_year_id')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.add_column('program', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('program_name_key'), 'program', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('program', 'department')
    op.drop_column('program', 'degree_name')
    op.drop_column('program', 'degree_title')
    op.drop_column('program', 'level')
    op.drop_column('program', 'code')
    op.drop_constraint(None, 'exam_session', type_='foreignkey')
    op.drop_table('exam')
    op.drop_table('course')
    op.drop_table('academic_year')
    op.drop_table('curriculum')
    program_level_enum = postgresql.ENUM(name='program_level_enum')
    program_level_enum.drop(op.get_bind())
    # ### end Alembic commands ###
